-- 书籍表
CREATE TABLE BOOK
(
    BOOK_ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    BOOK_NAME VARCHAR(255) DEFAULT 'NULL',
    BOOK_AUTHOR VARCHAR(255) DEFAULT 'NULL',
    BOOK_ISBN VARCHAR(255) NOT NULL,
    BOOK_VIEWS INTEGER DEFAULT 0,
    BOOK_MARKS INTEGER DEFAULT 0,
    BOOK_INTRODUCTION TEXT DEFAULT 'NULL',
    BOOK_PIC VARCHAR(255) DEFAULT 'NULL'
);

-- 读者表
CREATE TABLE READER
(
    READER_ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    READER_NAME VARCHAR(255) NOT NULL,
    READER_PASSWORD VARCHAR(255) NOT NULL,
    READER_EMAIL VARCHAR(255) NOT NULL
);
CREATE UNIQUE INDEX READER_READER_NAME_UINDEX ON READER (READER_NAME);
CREATE UNIQUE INDEX READER_READER_EMAIL_UINDEX ON READER (READER_EMAIL);

-- 官方标签/分类
CREATE TABLE TAG
(
    TAG_ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    TAG_NAME VARCHAR(255) NOT NULL
);
CREATE UNIQUE INDEX TAG_TAG_NAME_UINDEX ON TAG (TAG_NAME);

-- 读者书单
CREATE TABLE BOOKLIST
(
    BOOKLIST_ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    READER_ID INTEGER,
    BOOKLIST_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT BOOKLIST___READER FOREIGN KEY (READER_ID) REFERENCES READER (READER_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 官方书籍贴标签
CREATE TABLE BOOK_TAG
(
    ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    TAG_ID INTEGER,
    BOOK_ID INTEGER,
    CONSTRAINT BOOK_TAG___BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOK (BOOK_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT BOOK_TAG___TAG FOREIGN KEY (TAG_ID) REFERENCES TAG (TAG_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 读者读书笔记
CREATE TABLE NOTE
(
    NOTE_ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    READER_ID INTEGER,
    BOOK_ID INTEGER,
    NOTE_CONTENT TEXT,
    CONSTRAINT NOTE___BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOK (BOOK_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT NOTE___READER FOREIGN KEY (READER_ID) REFERENCES READER (READER_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 读者书房存书/读者关注的书/读者书单
CREATE TABLE READER_BOOK
(
    ID INTEGER AUTO_INCREMENT NOT NULL,
    READER_ID INTEGER NOT NULL,
    BOOK_ID INTEGER NOT NULL,
    REDAER_BOOK_STATUS INTEGER DEFAULT 0,
    BOOKLIST_ID INTEGER,
    CONSTRAINT REDAER_BOOK_READER_ID_BOOK_ID_PK PRIMARY KEY (READER_ID, BOOK_ID),
    CONSTRAINT READER_BOOK___READER FOREIGN KEY (READER_ID) REFERENCES  READER (READER_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT READER_BOOK___BOOK FOREIGN KEY (BOOK_ID) REFERENCES  BOOK (BOOK_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT REDAER_BOOK___BOOKLIST FOREIGN KEY (BOOKLIST_ID) REFERENCES BOOKLIST (BOOKLIST_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
-- CREATE UNIQUE INDEX CONSTRAINT_1E_INDEX_1 ON READER_BOOK (ID);

-- 读者自定义的标签
CREATE TABLE READER_TAG
(
    TAG_ID INTEGER AUTO_INCREMENT NOT NULL,
    READER_ID INTEGER NOT NULL,
    TAG_NAME VARCHAR(255),
    CONSTRAINT READER_TAG_READER_ID_TAG_ID_PK PRIMARY KEY (READER_ID, TAG_ID),
    CONSTRAINT READER_TAG___READER FOREIGN KEY (READER_ID) REFERENCES READER (READER_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
-- CREATE UNIQUE INDEX READER_BOOK_TAG___TAG_INDEX_1 ON READER_TAG (TAG_ID);

-- 读者书评
CREATE TABLE REVIEW
(
    REVIEW_ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    BOOK_ID INTEGER,
    READER_ID INTEGER,
    REVIEW_CONTENT TEXT,
    CONSTRAINT REVIEW___BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOK (BOOK_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT REVIEW___READER FOREIGN KEY (READER_ID) REFERENCES READER (READER_ID)
);

-- 读者书房数据贴自定义的标签
CREATE TABLE READER_BOOK_TAG
(
    ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    READER_ID INTEGER,
    BOOK_ID INTEGER NOT NULL,
    TAG_ID INTEGER,
    CONSTRAINT READER_BOOK_TAG___READER FOREIGN KEY (READER_ID) REFERENCES READER (READER_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT READER_BOOK_TAG___BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOK (BOOK_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT READER_BOOK_TAG___TAG FOREIGN KEY (TAG_ID) REFERENCES READER_TAG (TAG_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 读者为书评点赞
CREATE TABLE READER_LIKE_REVIEW
(
    ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    READER_ID INTEGER,
    REVIEW_ID INTEGER,
    CONSTRAINT READER_LIKE_REVIEW___READER FOREIGN KEY (READER_ID) REFERENCES READER (READER_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT READER_LIKE_REVIEW___REVIEW FOREIGN KEY (REVIEW_ID) REFERENCES REVIEW (REVIEW_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 关注关系
CREATE TABLE READER_FOLLOWER
(
    ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    READER_ID INTEGER,
    FOLLOW_ID INTEGER,
    CONSTRAINT READER_FOLLOWER___READER FOREIGN KEY (FOLLOW_ID) REFERENCES READER (READER_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX READER_FOLLOWER___READER_INDEX_1 ON READER (READER_ID, READER_ID);
CREATE INDEX READER_FOLLOWER___READER_INDEX_7 ON READER_FOLLOWER (READER_ID, FOLLOW_ID);